# -*- coding: utf-8 -*-
"""Ranking_10_Melhores_Faculdades _de _Odontologia_Brasil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nywyxUw2RApBWcGkOh-ZrPawH3V41kcI
"""

import matplotlib.pyplot as plt

# Dados do ranking
faculdades = ["USP", "UFMG", "Unesp", "Unicamp", "UFRGS", "UFRJ", "UFPR", "UFF", "UFSC", "UnB"]
ranking = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Criando o gráfico de barras
plt.figure(figsize=(10, 6))
plt.barh(faculdades, ranking, color='skyblue')
plt.xlabel('Ranking')
plt.ylabel('Faculdades')
plt.gca().invert_yaxis() # Invertendo o eixo Y para mostrar o 1º lugar no topo
plt.title('Ranking das 10 Melhores Faculdades de Odontologia do Brasil')
plt.show()
print("Fonte: RUF 2023 | Folha de São Paulo")
